# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='chat',
  serialized_pb=_b('\n\nchat.proto\x12\x04\x63hat\"\xd5\x01\n\x07Request\x12%\n\toperation\x18\x01 \x01(\x0e\x32\x12.chat.Request.Type\x12\x10\n\x08roomName\x18\x02 \x01(\t\x12\x14\n\x0croomPassword\x18\x03 \x01(\t\x12\x10\n\x08userName\x18\x04 \x01(\t\x12\x14\n\x0cuserPassword\x18\x05 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\"B\n\x04Type\x12\x0f\n\x0b\x43REATE_ROOM\x10\x00\x12\x0f\n\x0bJOIN_2_ROOM\x10\x01\x12\x0b\n\x07\x44\x45LIVER\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03\"\x87\x02\n\x08Response\x12&\n\toperation\x18\x01 \x01(\x0e\x32\x13.chat.Response.Type\x12-\n\nresultCode\x18\x02 \x01(\x0e\x32\x19.chat.Response.ResultCode\x12\x19\n\x11resultDescription\x18\x03 \x01(\t\x12\x10\n\x08roomName\x18\x04 \x01(\t\x12\x12\n\nsenderName\x18\x05 \x01(\t\"B\n\x04Type\x12\x0f\n\x0b\x43REATE_ROOM\x10\x00\x12\x0f\n\x0bJOIN_2_ROOM\x10\x01\x12\x0b\n\x07\x44\x45LIVER\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03\"\x1f\n\nResultCode\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='chat.Request.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_ROOM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN_2_ROOM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELIVER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=168,
  serialized_end=234,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_TYPE)

_RESPONSE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='chat.Response.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_ROOM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN_2_ROOM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELIVER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=168,
  serialized_end=234,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_TYPE)

_RESPONSE_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='chat.Response.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=469,
  serialized_end=500,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_RESULTCODE)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='chat.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='chat.Request.operation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roomName', full_name='chat.Request.roomName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roomPassword', full_name='chat.Request.roomPassword', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userName', full_name='chat.Request.userName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userPassword', full_name='chat.Request.userPassword', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='chat.Request.content', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=234,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='chat.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='chat.Response.operation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='chat.Response.resultCode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultDescription', full_name='chat.Response.resultDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roomName', full_name='chat.Response.roomName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='senderName', full_name='chat.Response.senderName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_TYPE,
    _RESPONSE_RESULTCODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=500,
)

_REQUEST.fields_by_name['operation'].enum_type = _REQUEST_TYPE
_REQUEST_TYPE.containing_type = _REQUEST
_RESPONSE.fields_by_name['operation'].enum_type = _RESPONSE_TYPE
_RESPONSE.fields_by_name['resultCode'].enum_type = _RESPONSE_RESULTCODE
_RESPONSE_TYPE.containing_type = _RESPONSE
_RESPONSE_RESULTCODE.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:chat.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
